version: "3"

services:
  backend_app:
    container_name: nodejs_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bridge_network
    environment:
      - APP_PORT=3000
      - DATABASE_URL=mongodb://mongo_database/AuthSystem
      - REDIS_URL=redis://redis_sv:6379

  mongodb:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bridge_network
    volumes:
      - authSystemVolume:/data/db

  redis_server:
    container_name: redis_sv
    image: redis
    ports:
      - 6379:6379
    volumes:
      - auth_system_redis:/data
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge

volumes:
  authSystemVolume:
    driver: local
  auth_system_redis:
    driver: local
